# frozen_string_literal: true
stage_types = [
  { 'coeficient' => ('0.035'),
    'name' => 'Barracão, lig. Provisórias, projetos',
    :steps_description => [{ 'singleFloor' => true,
                             'steps' => ['Projetos', 'Limpeza do terreno', 'Ligações água e Energia'], 'floorType' => 'initial' }] },
  { 'coeficient' => ('0.05'), 'name' => 'Infraestrututra (estacas, brocas, baldrames, sapatas)',
    :steps_description => [{ 'singleFloor' => true, 'steps' => ['Terraplenagem', 'Estacas e Gargantas', 'Baldrame'], 'floorType' => 'foundation' }] },
  { 'coeficient' => ('0.15'), 'name' => 'Supraestrutura (vigas, pilares, cintas, escadas)',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Concretagem pilares', 'Concretagem Vigas', 'Concretagem Lajes'], 'floorType' => 'floor' },
                           { 'singleFloor' => true, 'steps' => ['Estrutura Caixa de água e Platibanda'],
                             'floorType' => 'cover' }] },
  { 'coeficient' => ('0.08'), 'name' => 'Paredes e Painéis',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Alvenaria meia altura', 'Alvenaria até topo'], 'floorType' => 'floor' },
                           { 'singleFloor' => true, 'steps' => ['Alvenaria da Caixa de água e Platibanda'],
                             'floorType' => 'cover' }] },
  { 'coeficient' => ('0.09'), 'name' => 'Esquadrias',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Instalação Contramarco ', 'Esquadrias'], 'floorType' => 'floor' }] },
  { 'coeficient' => ('0.01'), 'name' => 'Vidros e Plásticos',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Vidros e Plásticos'], 'floorType' => 'floor' }] },
  { 'coeficient' => ('0.07'), 'name' => 'Coberturas (estrutura e telhas)',
    :steps_description => [{ 'singleFloor' => true, 'steps' => ['Estrutura do telhado', 'Colocação telhas', 'Calhas e rufos'], 'floorType' => 'cover' }] },
  { 'coeficient' => ('0.04'), 'name' => 'Impermeabilizações',
    :steps_description => [{ 'singleFloor' => true, 'steps' => ['Impermeabilização Fundação'], 'floorType' => 'foundation' },
                           { 'singleFloor' => false, 'steps' => ['Impermeabilização áreas molhadas'],
                             'floorType' => 'floor' }] },
  { 'coeficient' => ('0.08'), 'name' => 'Revestimentos Internos',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Chapisco Interno', 'Revestimento Ceramico - Parede', 'Emassamento parede', 'Reboco interno'], 'floorType' => 'floor' }] },
  { 'coeficient' => ('0.01'), 'name' => 'Forros',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Forro gesso'], 'floorType' => 'floor' }] },
  { 'coeficient' => ('0.045'), 'name' => 'Revestimentos Externos',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Chapisco Externo', 'Reboco Externo'], 'floorType' => 'floor' },
                           { 'singleFloor' => true, 'steps' => %w[Chapisco Reboco], 'floorType' => 'cover' }] },
  { 'coeficient' => ('0.09'), 'name' => 'Pisos',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Contrapiso ', 'Regularização Contrapiso', 'Base Armários', 'Contrapiso Externo', 'Piso ceramico', 'Finalização Piso Externo'], 'floorType' => 'floor' }] },
  { 'coeficient' => ('0.06'), 'name' => 'Pinturas',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Pintura 1 demão', 'Pintura 2 demão', 'Finalização Pintura'], 'floorType' => 'floor' },
                           { 'singleFloor' => true, 'steps' => ['Pintura'], 'floorType' => 'cover' }] },
  { 'coeficient' => ('0.012'), 'name' => 'Acabamentos (soleiras, rodapes, peitoril, etc.)',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Soleiras e Peitoris', 'Bancadas'], 'floorType' => 'floor' }] },
  { 'coeficient' => ('0.04'), 'name' => 'Instalações Elétricas e Telefônicas',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Caixas e conduítes laje', 'Caixas e conduítes alvenaria', 'Enfiação', 'Tomadas e interruptores'], 'floorType' => 'floor' },
                           { 'singleFloor' => true, 'steps' => ['Elétrica'], 'floorType' => 'cover' }] },
  { 'coeficient' => ('0.04'), 'name' => 'Instalações Hidráulicas',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Hidráulica ', 'Gás'], 'floorType' => 'floor' },
                           { 'singleFloor' => true, 'steps' => ['Caixa de água e barrilete'],
                             'floorType' => 'cover' }] },
  { 'coeficient' => ('0.04'), 'name' => 'Instalações: Esgoto e Águas Pluviais',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Esgoto', 'Água Pluvial'], 'floorType' => 'floor' }] },
  { 'coeficient' => ('0.045'), 'name' => 'Louças e Metais',
    :steps_description => [{ 'singleFloor' => false, 'steps' => ['Vasos sanitários e louças', 'Torneiras e metais'], 'floorType' => 'floor' }] },
  {  'coeficient' => ('0.013000000000000001'), 'name' => 'Complementos - limpeza geral e calafete',
     :steps_description => [{ 'singleFloor' => true, 'steps' => ['Conferências Gerais', 'limpeza geral e calafete', 'Legalização'], 'floorType' => 'end' }] },
  {  'coeficient' => ('0.0'), 'name' => 'Outros - Servicos complementares',
     :steps_description => [{ 'singleFloor' => true, 'steps' => ['Muro de arrimo', 'Piscina', 'Paisagismo', 'Armarios'], 'floorType' => 'end' }] },
  { 'name' => 'Outros', 'coeficient' => ('0'),
    :steps_description => [{ 'singleFloor' => false, 'steps' => [], 'floorType' => 'floor' }] }
]

stage_types.each do |stage_type|
  StageType.create!(stage_type)
end
